### ISSUE TITLE
issues since recent changes

### ISSUE THREAD

**Issue by SDUBZ** [kurotu/VRCQuestTools#5]
skin on quest side coming out diff colours like gold or green metallic
toggles etc coming out wrong or not working at all
not asure whats causing this since ive used all these methods before with no problems
only started happening recently

**Comment by kurotu** [comment]
Recently v1.1.0 has changed some code structures but I believe their logic are same.

Please make sure following points:
- Generated textures (in `Assets\KRT\QuestAvatars\<YOUR_AVATAR>\Textures\`) are correct.
- Turn on *VRCQuestTools* -> *Auto Remove Vertex Colors* from the menu bar.

If these don't make sense, would you provide screenshots and sample materials to inspect the issue?

**Comment by SDUBZ** [comment]
i always have remove vertex colours on
textures seem correct in the generated 
i cant send screenshots since im not on quest
i will get a zip of the avatar made by quest tools to see if you can maybe understand
what is happening for this to appear the way it is for quest users

**Comment by kurotu** [comment]
Sounds good. I’ll check your zip.

**Comment by SDUBZ** [comment]
[Jasmine.zip](https://github.com/kurotu/VRCQuestTools/files/7552234/Jasmine.zip)

**Comment by kurotu** [comment]
The zip doesn't have fbx, so I can't check the result. At least, I need a screenshot of Unity in order to know your expected result.

By the way, following typical practices may help you.

- You can test the converted avatar on PC by uploading with a new Blueprint ID. Quest users will see same one in most cases.
- You can get Quest screenshots from your friends who uses Quest.
- If your avatar uses shader's special features such as MatCap, Fur, etc., VRCQuestTools can't apply them. You'll need to tweak materials manually.

**Comment by SDUBZ** [comment]
here https://www.mediafire.com/file/bfrfv3ngc9w4u12/jasmine.zip/file

**Comment by kurotu** [comment]
I hid previous comment because it had some paid assets. PLEASE delete it from the online storage.

----

The issue is caused by Skin Colors animation of FX layer. Unexpectedly Poiyomi materials are used on Quest. Poiyomi doesn't work well for Quest, so it makes wrong skin appearance.

VRCQuestTools converts animation clips which change materials, but BlendTrees not. So the issue happens. For right now, you need to edit animation clips or materials to be changed by FX layer.

**Comment by kurotu** [comment]
I made a test version of VRCQuestTools and believe this properly converts blend trees.
You can download it from Artifacts section of following link. Would you try it?
https://github.com/kurotu/VRCQuestTools/actions/runs/1490647673

**Comment by SDUBZ** [comment]
> I made a test version of VRCQuestTools and believe this properly converts blend trees. You can download it from Artifacts section of following link. Would you try it? https://github.com/kurotu/VRCQuestTools/actions/runs/1490647673

yes i will do a conversion and see if one of my quest friends can say if its fixed or not

**Comment by kurotu** [comment]
Sorry, I missed some points. 

1. Test version had a small bug. Please use this link instead. https://github.com/kurotu/VRCQuestTools/actions/runs/1499470936
2. Please remove `Assets\KRT\VRCQuestTools` then import the test version because the old v0.7.0 is used in your project.
3. Perhaps you need to remove `Assets\KRT\VRCQuestTools\Tests` after importing. Somehow your project doesn't have some components such as NUnit. Tests folder is not needed at runtime.
4. Your avatar originally had missing materials (hair, corset and pants). This is a project specific issue, so I can't help. Please focus on body skin color at this time.
5. As written on the converter window, Poiyomi is not supported. So I can't assure about output textures.

**Comment by SDUBZ** [comment]
my friend said the skin textures look good my friend said on quest
