### ISSUE TITLE
Android Texture Compression makes larger bundle

### ISSUE THREAD

**Issue by ShayBox** [kurotu/VRCQuestTools#7]
**Describe the bug**
Enabling Android Texture Compression makes build size larger

**Environment**
- VRCQuestTools 1.6.1
- Unity 2019.4.31f1

**Additional context**
Texture Default Settings:
- Compression: High Quality
- Use Crunch Compression: True
- Compressor Quality: 100

My avatar (Auri) worked just fine before enabling "Android Texture Compression",  
~~But after my avatar failed to build for Quest (16MB), and I don't know what ATC is or how to disable it.~~  
~~I was only able to get the avatar to build again changing "Compression" to "Normal" quality, and only barely.~~
EDIT: I found how to change it, under Android you have to enable Override and change from ASTC to default "RGB Compressed ETC 4 Bits".

**Comment by kurotu** [comment]
If you completely don't want ASTC, please check following steps.
1. Open *File* -> *Build Settings*
2. Select Android platform
3. Change *Texture Compression* from `ASTC` to `Don't override` (Unity's default).
4. Uncheck *Show on startup* when *Unity Settings for Quest* window appears.

However, typically ASTC is recommended for Quest because it has better performance and quality than ETC. Meta(Oculus) recommends this, too.
https://developer.oculus.com/documentation/unity/unity-conf-settings/#build-settings

In Unity's ASTC setting, "RGB(A) Compressed ASTC 6x6 block" will be chosen. In order to keep ASTC and reduce build size (and get lesser quality), you can enable override with a larger block such as 8x8.

----

IMHO, it seems that your avatar has too many textures and meshes so that leads huge build size. You might get better result by removing unused mesh renderers, materials and textures from the avatar game object in the scene.

For example, my latest converted avatar has 14 assets of 1024x1024 ASTC textures and its compressed build size is 6.2MB.

![image](https://user-images.githubusercontent.com/74851548/170855295-ffd03597-e38e-428b-a400-55350392235e.png)
by https://github.com/MunifiSense/VRChat-Build-Size-Viewer

**Comment by ShayBox** [comment]
Makes sense, The build size viewer is really useful.  
My avatar does have a lot of materials, especially for quest, but the creator only provided a basic quest model with nothing working, no toggles, expressions, animations, so I and everyone else use the PC version on Quest and I don't have the experience enough to mess with combining materials and stuff like that.

**Comment by kurotu** [comment]
In my experience, texture size has major impact for build size. If you can allow lesser quality, reducing texture resolution or compression quality makes sense.
Otherwise, you should carefully choice meshes(fbx) and materials to include. The capacity is limited, so the basis is "Remove unused things" as I had written.

VRCQuestTools will not perform any optimization (probably forever). Because each avatar has its own various gimmicks and careless optimization might break them. For the same reason, I can't provide concrete advice. Sorry for inconvenience, please ask to who understands your avatar.

**Comment by ShayBox** [comment]
For anyone that may find this useful, I did some tests with various settings on my avatar.
My avatar is not optimized, it's a pc avatar on quest, you can reduce file size far more effectively optimizing it in Blender with CATS.

Editor & SDK:
- Unity 2018.4.41f1
- VRCSDK3-AVATAR-2022.06.03.00.04_Public.unitypackage

Texture Settings:
- Resolution: 2048
- Quality: High Quality
- Compression: 100

Compressed Build Size:
- Stock Unity: 9.2mb
- ATSC 4x4: 16.9mb
- ATSC 5x5: 15.0mb
- ATSC 6x6: 13.3mb
- ATSC 8x8: 10.7mb
